In [1]:
# ゼロ行列と単位行列の積の法則

import numpy as np
a = np.array([[2, 3, 4],  # 3×3の正方行列を作成
            [5, 6, 7],
            [8, 9, 1]])
zero = np.zeros((3, 3))    # 3×3のゼロ行列
unit = np.identity(3)      # 3×3の単位行列

In [2]:
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
unit

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
a*zero                     # AO = Oの法則

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.dot(a, unit)            # AE = EA = Aの法則

array([[2., 3., 4.],
       [5., 6., 7.],
       [8., 9., 1.]])