In [1]:
# 行列の成分の集計

import numpy as np
mtx = np.array([[10, 20, 30],  # 3×3の行列を作成
                [40, 50, 60],
                [70, 80, 90]]
            )

In [2]:
np.max(mtx)          # 全成分の最大値

90

In [3]:
np.min(mtx)          # 全成分の最小値

10

In [4]:
np.sum(mtx)          # 全成分の合計

450

In [5]:
np.mean(mtx)         # 全成分の平均

50.0

In [6]:
# 行列の列ごと、行ごとの集計
np.sum(mtx, axis=0)  # 列ごとの合計

array([120, 150, 180])

In [7]:
np.mean(mtx, axis=0) # 列ごとの平均

array([40., 50., 60.])

In [8]:
np.sum(mtx, axis=1) # 行ごとの合計

array([ 60, 150, 240])

In [9]:
np.mean(mtx, axis=1) # 行ごとの平均

array([20., 50., 80.])