In [1]:
# sin、cos、tanの計算

import numpy as np
x = np.array([0, 1])

In [2]:
np.sin(x)

array([0.        , 0.84147098])

In [3]:
np.sin(np.pi * 0.5)   # π/2のときのサインの値は1

1.0

In [4]:
np.cos(x)

array([1.        , 0.54030231])

In [5]:
np.cos(np.pi * 0.5)    # 0になる

6.123233995736766e-17

In [6]:
np.tan(x)

array([0.        , 1.55740772])

In [7]:
np.tan(np.pi * 0.5)    # 無限に発散する

1.633123935319537e+16

In [8]:
np.pi  # 円周率

3.141592653589793