In [11]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
print(x)
print(x.dtype)

[1 2 3 4 5]
int32


In [12]:
x = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
print(x)
print(x.dtype)

[1. 2. 3. 4. 5.]
float64


In [13]:
# float32型を指定
x = np.array([1, 2, 3, 4, 5], dtype=np.float32)
print(x)
print(x.dtype)

[1. 2. 3. 4. 5.]
float32


In [14]:
# 文字列で指定
x = np.array([1, 2, 3, 4, 5], dtype='float32')
print(x)
print(x.dtype)

[1. 2. 3. 4. 5.]
float32
