In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [2]:
# 足し算
x + 10

array([11, 12, 13, 14, 15])

In [3]:
# 引き算
x - 1

array([0, 1, 2, 3, 4])

In [4]:
# 掛け算
x*10

array([10, 20, 30, 40, 50])

In [5]:
# 割り算
x/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [6]:
# 割り算の結果を整数だけにする
x//2

array([0, 1, 1, 2, 2], dtype=int32)

In [7]:
# 剰余
x%2

array([1, 0, 1, 0, 1], dtype=int32)