In [3]:
# 切り捨て、切り上げ、四捨五入を行う

import numpy as np
x = np.array([-1.8, -1.4, -1.0, -0.6, -0.2, 0., 0.2, 0.6, 1.0, 1.4, 1.8])

In [4]:
np.floor(x)  # 切り捨て(値が小さい方の整数にする)

array([-2., -2., -1., -1., -1.,  0.,  0.,  0.,  1.,  1.,  1.])

In [5]:
np.trunc(x)  # 切り捨て(小数部分を切り捨てる)

array([-1., -1., -1., -0., -0.,  0.,  0.,  0.,  1.,  1.,  1.])

In [6]:
np.ceil(x)   # 切り上げ（大きい方の整数にする)

array([-1., -1., -1., -0., -0.,  0.,  1.,  1.,  1.,  2.,  2.])

In [7]:
np.round(x)  # 四捨五入

array([-2., -1., -1., -1., -0.,  0.,  0.,  1.,  1.,  1.,  2.])

In [8]:
np.around(x)  # 四捨五入

array([-2., -1., -1., -1., -0.,  0.,  0.,  1.,  1.,  1.,  2.])

In [9]:
np.rint(x)    # 四捨五入

array([-2., -1., -1., -1., -0.,  0.,  0.,  1.,  1.,  1.,  2.])

In [10]:
np.fix(x)     # 0に近い方の整数をとる

array([-1., -1., -1., -0., -0.,  0.,  0.,  0.,  1.,  1.,  1.])