In [6]:
# ラジアンと度を相互変換する

import numpy as np
x = np.array([90, 180, 270])

In [7]:
# ラジアンに変換
np.radians(x)

array([1.57079633, 3.14159265, 4.71238898])

In [8]:
np.deg2rad(x)              # ラジアンに変換

array([1.57079633, 3.14159265, 4.71238898])

In [9]:
np.rad2deg(np.deg2rad(x))  # ラジアンを度に変換

array([ 90., 180., 270.])