In [5]:
# ベクトルの成分の累乗を求める

import numpy as np

x = np.array([1, 2, 3, 4, 5])
np.power(x, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [6]:
x**2

array([ 1,  4,  9, 16, 25])

In [3]:
# ベクトルの成分の平方根を求める

x = np.array([1, 2, 3, 4, 5])
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])