In [3]:
# sin、cos、tanの逆関数の計算

import numpy as np
x = np.array([0.5, 1])
np.arcsin(np.sin(x)) # sinの逆関数

array([0.5, 1. ])

In [4]:
np.arccos(np.cos(x)) # cosの逆関数

array([0.5, 1. ])

In [5]:
np.arctan(np.tan(x)) # tanの逆関数

array([0.5, 1. ])